### ISSUE TITLE
Could not find a file named "pubspec.yaml"

### ISSUE THREAD

**Issue by nuonveyo** [FlutterEurope/conference2020#54]
After i clone soft code and run to test, i got an error:

Could not find a file named "pubspec.yaml" in "C:\flutter\.pub-cache\git\feature_discovery-e2843138962a1c7beea1f2782e519b468e2ccdbb".

Could you help me please!

**Comment by orestesgaolin** [comment]
Seems like Flutter cannot fetch package from GitHub (maybe you don't have
ssh access configured). Try to replace ssh link to feature discovery
package with https.

pon., 20 sty 2020, 04:01 użytkownik Veyo <notifications@github.com> napisał:
