### ISSUE TITLE
Talks are not loading version 1.5 (36)

### ISSUE THREAD

**Issue by wwwdata** [FlutterEurope/conference2020#55]
After updating to version 1.5 (36) on iOS I only see the loading spinner but no talks ever load for me. Restarting the app does not work. I did not try reinstalling so far because I don’t want to lose my favorites.

**Comment by wwwdata** [comment]
Never mind. Now after a couple more restarts it works again

**Comment by orestesgaolin** [comment]
Thanks for the report. Seems like we had some issue on the backend. Please let us know if you encounter this again.
