### ISSUE TITLE
builds fine, app doesn't start

### ISSUE THREAD

**Issue by Lagily** [FlutterEurope/conference2020#57]
Hey guys

When I build the project locally everything seems to be okay, I also added a google-services.json of my own. But when I try to launch it in VSCode, it hangs at the 'installing' message and starts the app for a second and closes it after immediately. No output in the debug terminal. Do you have any ideas? Can you supply your launch.json to me?

![image](https://user-images.githubusercontent.com/42535205/73755687-b0670800-4766-11ea-8864-08bbcad39eae.png)

Best regards
Ali

**Comment by orestesgaolin** [comment]
Hi, thanks for reporting the issue.

The launch.json is [available in the repository](https://github.com/FlutterEurope/conference2020/blob/master/.vscode/launch.json).

Isn't there anything else in the output log?

**Comment by Lagily** [comment]
Unfortunately not, that is all the output and pub get also ran fine
I will try to downgrade my jdk maybe there is some issue with my installed JDK 12

**Comment by orestesgaolin** [comment]
I'd love to help you but atm there's nothing I can think of :/ My colleagues tried this on their machines and it launched just fine.

**Comment by Lagily** [comment]
A 'simple' flutter clean was enough to make it work, thanks for the help!
