### ISSUE TITLE
DEV Contentful access

### ISSUE THREAD

**Issue by Lagily** [FlutterEurope/conference2020#58]
Hi there

Not quite sure, what the best way to contact you directly is, but could I get access to the Contentful and Firebase backends, at least for Dev?

Best regards
Ali

**Comment by Lagily** [comment]
Also, under what license is this source code? Could you add a license?

**Comment by orestesgaolin** [comment]
Sure, gonna add some LICENSE file soon. I need to think which one would be the best.

Please [drop me an email](https://github.com/orestesgaolin), and I'll send you something to work with.
