### ISSUE TITLE
Reusing this project 

### ISSUE THREAD

**Issue by jonathangull** [FlutterEurope/conference2020#60]
Folks
Is it possible to make this project run in stable channel ? if so are there any tips? I tried to get this to work on Dev channel but number of build errors are huge not to mention the build times. Any suggestions the best course of action for me to reuse this project for one of the conferences I am helping setup.

**Comment by orestesgaolin** [comment]
Hi, I will try to migrate this in future, but right now I'm extremely busy so cannot guarantee anything. Thanks for the interest!

**Comment by jonathangull** [comment]
Hello Dominik, Thank you mate, totally understand, Let me see if I can get this work in stable channel and share to community. Thanks again , keep up the good work.
